/**
 * AUTO-GENERATED input field definitions for n8n fixedCollection UI
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: pnpm generate:schemas
 * Generated: 2026-03-12T19:07:19.760Z
 */

export interface InputFieldDef {
	name: string;
	type: "string" | "number" | "boolean" | "options";
	required: boolean;
	description: string;
	placeholder?: string;
	options?: Array<{ name: string; value: string }>;
}

export const inputSchemas: Record<string, InputFieldDef[]> = {
	"instagram-comments": [
		{ name: "url", type: "string", required: true, description: "Instagram post URL", placeholder: "https://www.instagram.com/p/postId" },
	],
	"instagram-posts": [
		{ name: "url", type: "string", required: true, description: "Instagram post URL", placeholder: "https://www.instagram.com/p/postId" },
	],
	"instagram-profiles": [
		{ name: "url", type: "string", required: true, description: "Instagram profile URL", placeholder: "https://www.instagram.com/username" },
	],
	"instagram-reels": [
		{ name: "url", type: "string", required: true, description: "Instagram reel URL", placeholder: "https://www.instagram.com/reel/ABC123" },
	],
	"linkedin-companies": [
		{ name: "url", type: "string", required: true, description: "LinkedIn company URL", placeholder: "https://www.linkedin.com/company/company-name" },
	],
	"linkedin-jobs": [
		{ name: "url", type: "string", required: true, description: "LinkedIn job listings URL", placeholder: "https://www.linkedin.com/jobs/view/1234567890" },
	],
	"linkedin-people-search": [
		{ name: "url", type: "string", required: true, description: "LinkedIn search URL", placeholder: "https://www.linkedin.com/search/results/people/" },
		{ name: "first_name", type: "string", required: false, description: "First name to search by", placeholder: "John" },
		{ name: "last_name", type: "string", required: false, description: "Last name to search by", placeholder: "Doe" },
	],
	"linkedin-posts": [
		{ name: "url", type: "string", required: true, description: "LinkedIn post URL", placeholder: "https://www.linkedin.com/posts/username_activity" },
	],
	"linkedin-profiles": [
		{ name: "url", type: "string", required: true, description: "LinkedIn profile URL", placeholder: "https://www.linkedin.com/in/username" },
	],
	"tiktok-comments": [
		{ name: "url", type: "string", required: true, description: "Specific post URL", placeholder: "https://www.tiktok.com/@user/video/1234567890" },
	],
	"tiktok-posts": [
		{ name: "url", type: "string", required: true, description: "TikTok video URL", placeholder: "https://www.tiktok.com/@username/video/videoId" },
	],
	"tiktok-profiles": [
		{ name: "url", type: "string", required: true, description: "TikTok profile URL", placeholder: "https://www.tiktok.com/@username" },
	],
	"twitter-posts": [
		{ name: "url", type: "string", required: true, description: "Twitter/X post URL", placeholder: "https://twitter.com/username/status/tweetId" },
	],
	"twitter-profiles": [
		{ name: "url", type: "string", required: true, description: "Twitter/X profile URL", placeholder: "https://twitter.com/username" },
	],
	"youtube-channels": [
		{ name: "url", type: "string", required: true, description: "YouTube channel URL", placeholder: "https://www.youtube.com/@channelname" },
	],
	"youtube-comments": [
		{ name: "url", type: "string", required: true, description: "YouTube video URL", placeholder: "https://www.youtube.com/watch?v=videoId" },
		{ name: "load_replies", type: "number", required: false, description: "Number of replies to load per comment" },
		{ name: "num_of_comments", type: "number", required: false, description: "Maximum number of comments to fetch" },
		{ name: "sort_by", type: "options", required: false, description: "Sort order for comments", options: [{ name: "Top", value: "top" }, { name: "Newest", value: "newest" }] },
	],
	"youtube-videos": [
		{ name: "url", type: "string", required: true, description: "YouTube video URL", placeholder: "https://www.youtube.com/watch?v=videoId" },
	],
	"facebook-comments": [
		{ name: "url", type: "string", required: true, description: "Facebook post URL", placeholder: "https://www.facebook.com/username/posts/123456" },
	],
	"facebook-groups": [
		{ name: "url", type: "string", required: true, description: "Facebook group URL", placeholder: "https://www.facebook.com/groups/groupname" },
	],
	"facebook-posts": [
		{ name: "url", type: "string", required: true, description: "Facebook post URL", placeholder: "https://www.facebook.com/username/posts/123456" },
	],
	"facebook-profiles": [
		{ name: "url", type: "string", required: true, description: "Facebook profile or post URL", placeholder: "https://www.facebook.com/username" },
	],
	"facebook-reels": [
		{ name: "url", type: "string", required: true, description: "Facebook profile URL", placeholder: "https://www.facebook.com/username" },
	],
	"indeed-companies": [
		{ name: "url", type: "string", required: true, description: "Indeed company profile URL", placeholder: "https://www.indeed.com/cmp/..." },
	],
	"indeed-jobs": [
		{ name: "url", type: "string", required: true, description: "Indeed job listing URL", placeholder: "https://www.indeed.com/viewjob?jk=..." },
	],
	"glassdoor-companies": [
		{ name: "url", type: "string", required: true, description: "Glassdoor company profile URL", placeholder: "https://www.glassdoor.com/Overview/..." },
	],
	"glassdoor-jobs": [
		{ name: "url", type: "string", required: true, description: "Glassdoor job listing URL", placeholder: "https://www.glassdoor.com/job-listing/..." },
	],
	"glassdoor-reviews": [
		{ name: "url", type: "string", required: true, description: "Glassdoor company reviews URL", placeholder: "https://www.glassdoor.com/Reviews/..." },
	],
	"yelp-businesses": [
		{ name: "url", type: "string", required: true, description: "Yelp business profile URL", placeholder: "https://www.yelp.com/biz/..." },
	],
	"yelp-reviews": [
		{ name: "url", type: "string", required: true, description: "Yelp business reviews URL", placeholder: "https://www.yelp.com/biz/..." },
	],
	"github-repositories": [
		{ name: "url", type: "string", required: true, description: "GitHub repository URL", placeholder: "https://github.com/user/repo" },
	],
	"crunchbase-companies": [
		{ name: "url", type: "string", required: true, description: "Crunchbase company profile URL", placeholder: "https://www.crunchbase.com/organization/..." },
	],
};
